title: theWritingDev
subtitle: "Devs writing Blog Entries"
description: "Devs writing Blog Entries"
author: PartyGuy
language: en
timezone: UTC

url: https://thewritingdev.netlify.com
root: /
permalink: posts/:year/:month/:day/:title/
archive_dir: posts
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

theme: navy
deploy:
  type: git
  repo: git@github.com:hexojs/hexojs.github.io.git

highlight:
  enable: true
  line_number: false

disqus_shortname: 
google_analytics: 
fb_admins: 
algolia:
  en:
    api_key: 
    index_name: 
twitter: partyguy01
github: partyguy01/thewritingdev
